---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dev-roboscale-io-v1alpha1-devspace
  failurePolicy: Fail
  name: mdevspace.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - devspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dev-roboscale-io-v1alpha1-workspacemanager
  failurePolicy: Fail
  name: mworkspacemanager.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspacemanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dev-roboscale-io-v1alpha1-devspaceide
  failurePolicy: Fail
  name: mdevspaceide.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - devspaceides
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dev-roboscale-io-v1alpha1-devspacevdi
  failurePolicy: Fail
  name: mdevspacevdi.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - devspacevdis
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dev-roboscale-io-v1alpha1-devspace
  failurePolicy: Fail
  name: vdevspace.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - devspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dev-roboscale-io-v1alpha1-workspacemanager
  failurePolicy: Fail
  name: vworkspacemanager.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspacemanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dev-roboscale-io-v1alpha1-devspaceide
  failurePolicy: Fail
  name: vdevspaceide.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - devspaceides
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dev-roboscale-io-v1alpha1-devspacevdi
  failurePolicy: Fail
  name: vdevspacevdi.kb.io
  rules:
  - apiGroups:
    - dev.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - devspacevdis
  sideEffects: None
