---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-buildmanager
  failurePolicy: Fail
  name: mbuildmanager.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buildmanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-robot-roboscale-io-v1alpha1-robot
  failurePolicy: Fail
  name: mrobot.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robots
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-buildmanager
  failurePolicy: Fail
  name: vbuildmanager.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buildmanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-robot-roboscale-io-v1alpha1-robot
  failurePolicy: Fail
  name: vrobot.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robots
  sideEffects: None
