# permissions for end users to view devspacejupyters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: devspacejupyter-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devspace-operator
    app.kubernetes.io/part-of: devspace-operator
    app.kubernetes.io/managed-by: kustomize
  name: devspacejupyter-viewer-role
rules:
- apiGroups:
  - dev.roboscale.io
  resources:
  - devspacejupyters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dev.roboscale.io
  resources:
  - devspacejupyters/status
  verbs:
  - get
