# permissions for end users to view devspaceides.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: devspaceide-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: robot-operator
    app.kubernetes.io/part-of: robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: devspaceide-viewer-role
rules:
- apiGroups:
  - dev.roboscale.io
  resources:
  - devspaceides
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dev.roboscale.io
  resources:
  - devspaceides/status
  verbs:
  - get
