# permissions for end users to view robotartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: robotartifact-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: robot-operator
    app.kubernetes.io/part-of: robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: robotartifact-viewer-role
rules:
- apiGroups:
  - robot.roboscale.io
  resources:
  - robotartifacts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - robotartifacts/status
  verbs:
  - get
