---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - buildmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - buildmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - buildmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - discoveryservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - discoveryservers/finalizers
  verbs:
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - discoveryservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - launchmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - launchmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - launchmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - robots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - robots/finalizers
  verbs:
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - robots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - rosbridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - rosbridges/finalizers
  verbs:
  - update
- apiGroups:
  - robot.roboscale.io
  resources:
  - rosbridges/status
  verbs:
  - get
  - patch
  - update
