apiVersion: robot.roboscale.io/v1alpha1
kind: MetricsExporter
metadata:
  labels:
    app.kubernetes.io/name: metricsexporter
    app.kubernetes.io/instance: metricsexporter-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: metricsexporter-sample
spec:
  # TODO(user): Add fields here
