processor:
  ignoreTypes:
    - "List$"
  sortKinds:
    - "Robot"
    - "WorkspaceManager"
    - "RobotDevSuite"
    - "RobotVDI"
    - "DevSpaceIDE"
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: 1.22
